# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a200tsbv484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.cache/wt [current_project]
set_property parent.project_path D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/imports/Desktop/rep_mem_in0.txt
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/imports/Desktop/exponent_values.mem
}
read_verilog -library xil_defaultlib {
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/mlp_adder.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/mlp_mult.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/mlp_unit.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/mlp_mult_tb.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/imports/new/mlp_unit_tb.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/exponent_mem.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/mlp_full.v
  D:/BarIlan/DDP/exercises/tutorial/vision_transformer_project/vision_transformer/8.6.23/MLP_final/MLP/MLP.srcs/sources_1/new/defines.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mlp_unit -part xc7a200tsbv484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mlp_unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mlp_unit_utilization_synth.rpt -pb mlp_unit_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
